# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: source
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

# SEO settings
title: TriVols
description: "Club of Triathletes at the University of Tennessee competing in the Southeast Collegiate Triathlon Conference"
keywords: "triathlon, Tennessee, Knoxville, triathlete, UTK, bikes, SECTC"

# Site settings
url: http://trivols.org
baseurl: ""
# baseurl: ""

# Author settings
author:
  name      : Alex Pawlowski
  job       : President
  bio       : "Triathlete, PhD student at UT, love to compete and enjoy every moment"
  thumb     : /images/author.jpg
  email     : apawlows@vols.utk.edu
  url       : http://alexpawlowski.me
  github    : http://github.com/alexpawlowski
  twitter   : http://twitter.com/alexpawlowski_
  linkedin  : http://linkedin.com/in/alexpawlowski

# google_analytics: UA-52446115-1
repo: http://github.com/trivols/trivols.github.io

# comments
disqus_shortname: "alexpawlowski"
